proseWrap: always
plugins:
  - "@trivago/prettier-plugin-sort-imports"
  - "prettier-plugin-sh"
importOrder:
  - "node"
  - "^vue"
  - "^vitepress"
  - "^[^.]"
  - "^[./]"
importOrderSeparation: true
importOrderSortSpecifiers: true
